# Generated by Django 3.1.7 on 2021-05-21 20:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('Issuedate', models.DateTimeField()),
                ('DueDate', models.DateTimeField()),
                ('ReturnDate', models.DateTimeField(default=datetime.datetime(2021, 5, 22, 1, 46, 13, 764096))),
                ('BookStatus', models.CharField(default='True', max_length=10)),
                ('Fine', models.IntegerField(default=0)),
                ('Comment', models.CharField(default='Good', max_length=200)),
                ('IdKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='need.studentrecord')),
            ],
        ),
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('Issuedate', models.DateTimeField(auto_now_add=True)),
                ('DueDate', models.DateTimeField(default=datetime.datetime(2021, 6, 6, 1, 46, 13, 763096))),
                ('BookStatus', models.CharField(default='False', max_length=10)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='need.studentrecord')),
            ],
        ),
    ]
