# Generated by Django 3.1.7 on 2021-05-21 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='DueDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 1, 47, 0, 236752)),
        ),
        migrations.AlterField(
            model_name='historyrecord',
            name='ReturnDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 1, 47, 0, 237752)),
        ),
    ]
