# Generated by Django 3.1.7 on 2021-05-21 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0004_auto_20210522_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyrecord',
            name='ReturnDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 2, 7, 12, 878647)),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='DueDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 2, 7, 12, 877648)),
        ),
    ]
