# Generated by Django 3.1.7 on 2021-05-28 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0005_auto_20210522_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='DueDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 23, 51, 40, 601663)),
        ),
        migrations.AlterField(
            model_name='historyrecord',
            name='ReturnDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 23, 51, 40, 601663)),
        ),
    ]
